:: Isaya : changes to operate from the Chloe directory instead of the game directory
@echo off

:: Sounds
del override\chloe0.wav
del override\chloe1.wav
del override\chloe2.wav
del override\chloe3.wav
del override\chloe8.wav
del override\chloe9.wav
del override\chloea.wav
del override\chloeb.wav
del override\chloec.wav
del override\chloed.wav
del override\chloee.wav
del override\chloef.wav
del override\chloeg.wav
del override\chloeg10.wav
del override\chloeg11.wav
del override\chloeg12.wav
del override\chloeg13.wav
del override\chloeg14.wav
del override\chloeg15.wav
del override\chloegp1.wav
del override\chloegp2.wav
del override\chloegp3.wav
del override\chloegp4.wav
del override\chloegp5.wav
del override\chloegp6.wav
del override\chloegp7.wav
del override\chloegp8.wav
del override\chloegp9.wav
del override\chloeh.wav
del override\chloei.wav
del override\chloej.wav
del override\chloek.wav
del override\chloel.wav
del override\chloel1.wav
del override\chloel2.wav
del override\chloel3.wav
del override\chloel4.wav
del override\chloel5.wav
del override\chloel6.wav
del override\chloel6b.wav
del override\chloel6c.wav
del override\chloel7.wav
del override\chloel8.wav
del override\chloel8b.wav
del override\chloem.wav
del override\chloen.wav
del override\chloeo.wav
del override\chloep.wav
del override\chloeq.wav
del override\chloer.wav
del override\chloes.wav
del override\chloet.wav
del override\chloeu.wav
del override\chloev.wav
del override\chloew.wav
del override\chloex.wav
del override\chloey.wav
del override\chloez.wav
del override\chloe_.wav

:: Music
del override\ChGTKUCR.wav
del override\ChImCR.wav
del override\ChLoveCR.wav
